{{- if not .Values.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reactive-resume.jwt-secret-name" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "reactive-resume.jwt-secret-name" . )) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $jwtSecret := (get $secretData "JWT_SECRET") | default (randAlphaNum 64 | b64enc) }}
  JWT_SECRET: {{ $jwtSecret | b64enc | quote }}
{{- end }}