{{- if not .Values.secretKey }}
secret_key_is: {{ .Values.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reactive-resume.secert-key-name" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "reactive-resume.secert-key-name" . )) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := (get $secretData "SECRET_KEY") | default (randAlphaNum 64 | b64enc) }}
  {{- $secretKey := (get $secretData "JWT_SECRET") | default (randAlphaNum 64 | b64enc) }}
  SECRET_KEY: {{ $secretKey | b64enc | quote }}
  JWT_SECRET: {{ $JwtSecret | b64enc | quote }}
{{- end }}
