apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-resume.fullname" . }}
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: frontend-http
      protocol: TCP
      name: http
  selector:
    {{- include "reactive-resume.selectorLabels" . | nindent 4 }}
